version: '3'

services:
  nextjs-app:
    build:
      context: ./react-ad-campaigns
    ports:
      - "3000:3000"

  go-app:
    build:
      context: ./go-ad-campaigns
    ports:
      - "8080:8080"

  nginx-proxy:
    image: nginx
    ports:
      - "5000:80"
    depends_on:
      - nextjs-app
      - go-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
